### ISSUE TITLE
Normalize the formatting

### ISSUE THREAD

**Issue by JohnAZoidberg** [dhbw-stginf16a/java-banking1#2]
Make sure all classes conform to the [standard formatting](http://www.oracle.com/technetwork/java/codeconventions-150003.pdf)
IntelliJ IDEA provides  CTRL+ALT+L to do this.

**Comment by guserav** [comment]
we could enable automatic formating in every commit if you do it via intellij

**Comment by JohnAZoidberg** [comment]
Reformatting done with 4cd41997efde653e5c804265af56568bbe9fb705
